trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  javaVersion: '17'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '$(javaVersion)'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    
    - task: Gradle@3
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '$(javaVersion)'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'clean build test jacocoTestReport'

    # Archive build outputs and test reports
    - task: CopyFiles@2
      inputs:
        contents: |
          **/build/**
          **/build/reports/jacoco/**
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'build-outputs'

    # Publish code coverage results
    - task: PublishCodeCoverageResults@2
      inputs:
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/build/reports/jacoco/test/jacocoTestReport.xml'
        pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java/'
        failIfCoverageEmpty: true

- stage: CodeAnalysis
  jobs:
  - job: SonarCloudAnalysis
    steps:
    - checkout: self
      fetchDepth: 0

    # Download build artifacts for analysis
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'build-outputs'
        downloadPath: '$(System.DefaultWorkingDirectory)'

    - task: SonarCloudPrepare@3
      inputs:
        SonarCloud: 'SonarConnection'
        organization: 'x00078774'
        scannerMode: 'other'
        extraProperties: |
          # Additional properties that will be passed to the scanner
          sonar.projectKey='X00078774_DevOps_CA3'
          sonar.projectName='DevOps_CA3'
          sonar.java.binaries=$(System.DefaultWorkingDirectory)/**/build/classes
          sonar.coverage.jacoco.xmlReportPaths=$(System.DefaultWorkingDirectory)/**/build/reports/jacoco/test/jacocoTestReport.xml
          sonar.junit.reportPaths=$(System.DefaultWorkingDirectory)/**/build/test-results/test
          sonar.java.libraries=$(System.DefaultWorkingDirectory)/**/build/libs/*.jar

    - task: Gradle@3
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '$(javaVersion)'
        jdkArchitectureOption: 'x64'
        tasks: 'sonar'

    - task: SonarCloudPublish@3
      inputs:
        pollingTimeoutSec: '300'