trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  javaVersion: '17'

stages:
# Stage 1: Build
- stage: Build
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '$(javaVersion)'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
    
    - task: Gradle@3
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '$(javaVersion)'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        tasks: 'clean build test jacocoTestReport'

    - task: CopyFiles@2
      inputs:
        contents: |
          **/build/**
          **/build/reports/jacoco/**
        targetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'build-outputs'

    - task: PublishCodeCoverageResults@2
      inputs:
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/build/reports/jacoco/test/jacocoTestReport.xml'
        pathToSources: '$(System.DefaultWorkingDirectory)/src/main/java/'
        failIfCoverageEmpty: true

# Stage 2: CodeAnalysis
- stage: CodeAnalysis
  jobs:
  - job: SonarCloudAnalysis
    displayName: 'SonarCloud Analysis'
    steps:
    - checkout: self
      fetchDepth: 0

    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'build-outputs'
        downloadPath: '$(System.DefaultWorkingDirectory)'

    - task: SonarCloudPrepare@3
      inputs:
        SonarCloud: 'SonarConnection'
        organization: 'x00078774'
        scannerMode: 'other'
        extraProperties: |
          # Additional properties that will be passed to the scanner
          sonar.projectKey='X00078774_DevOps_CA3'
          sonar.projectName='DevOps_CA3'
          sonar.java.binaries=$(System.DefaultWorkingDirectory)/**/build/classes
          sonar.coverage.jacoco.xmlReportPaths=$(System.DefaultWorkingDirectory)/**/build/reports/jacoco/test/jacocoTestReport.xml
          sonar.junit.reportPaths=$(System.DefaultWorkingDirectory)/**/build/test-results/test
          sonar.java.libraries=$(System.DefaultWorkingDirectory)/**/build/libs/*.jar

    - task: Gradle@3
      inputs:
        workingDirectory: ''
        gradleWrapperFile: 'gradlew'
        gradleOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '$(javaVersion)'
        jdkArchitectureOption: 'x64'
        tasks: 'sonar'

    - task: SonarCloudPublish@3
      inputs:
        pollingTimeoutSec: '300'

# Stage 3: SecurityScanning
- stage: SecurityScanning
  displayName: 'Security Scanning'
  jobs:
  - job: SecurityCheck
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'build-outputs'
        downloadPath: '$(System.DefaultWorkingDirectory)'

    - task: MicrosoftSecurityDevOps@1
      inputs:
        categories: 'sources'
        break: false
        tools: 'credscan'
        sourcePath: '$(System.DefaultWorkingDirectory)'

# Stage 4: DependencySecurity
- stage: DependencySecurity
  displayName: 'Dependency Security Scanning'
  jobs:
  - job: OWASPCheck
    steps:
    - task: dependency-check-build-task@6
      inputs:
        projectName: '$(Build.Repository.Name)'
        scanPath: '$(System.DefaultWorkingDirectory)'
        format: 'HTML'
        uploadReports: true
        uploadSARIFReport: true
        failOnCVSS: '7'
        nvdApiKey: '2c3d82d7-c688-49e1-970b-254e2295ab36'

# Stage 5: Deployment
- stage: Deploy
  jobs:
  - deployment: DeployJob
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'Test'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '$(javaVersion)'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'
          
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'build-outputs'
              downloadPath: '$(System.ArtifactsDirectory)'
          
          - script: |
              echo "Deploying application..."
              echo "Deployment completed."
            displayName: 'Deploy Application'
